[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"

[build.environment]
  # Supabase Configuration
  VITE_SUPABASE_URL = "https://yrvicwapjsevyilxdzsm.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlydmljd2FwanNldnlpbHhkenNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMDY2ODIsImV4cCI6MjA3NTU4MjY4Mn0.tRhpswJI2CccGdWX3fcJEowSA9IBh-KMYHfaiKVjN7c"
  
  # App Configuration
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
  # Build Settings
  VITE_APP_ENVIRONMENT = "production"
  VITE_ENABLE_DEBUG = "false"
  
  # Enable build plugins
  NETLIFY_USE_YARN = "true"
  
  # Enable Next.js support (if needed)
  # NEXT_TELEMETRY_DISABLED = "1"